---

- hosts: localhost
  tasks:
  - name: Update homebrew itself first
    homebrew: update_homebrew=yes

  - name: Remove homebrew cask packages
    homebrew: name={{ item }} state=absent
    with_items:
      - clipy

  - name: Install Homebrew cask packages
    homebrew_cask: name={{ item }}
    with_items:
      - google-chrome
      - google-japanese-ime
      - firefox
      - adobe-acrobat-reader
      - macdown
      # - bitbar
      # - karabiner
      # - karabiner-elements
      - dropbox
      - slack
      - chatwork
      # - evernote
      - skitch
      - alfred
      # - near-lock
      # - 1password
      - sublime-text
      - omnifocus
      - caskroom/versions/omnigraffle6
      - qlmarkdown
      - qlimagesize
      - qlcolorcode
      - qlvideo
      - qlstephen
      - qlgradle
      - qlprettypatch
      - quicklook-csv
      - quicklook-json
      - betterzipql
      - inkdrop
      - lightpaper
      - typora
      - appcleaner
